# List the start up tasks. All this happens when you first open this. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  #https://github.com/aws/aws-cdk?tab=readme-ov-file#getting-started
  - name: cdk
    before: |
      npm i -g aws-cdk

  - name: terraform
    before: |
      ./bin/terraform-cli-install.sh

  #random utilities
  - name: utils
    before: |
      sudo apt-get install tree


  - name: powershell
    before: |
      ./bin/powershell-cli-install.sh

  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      ./bin/aws-cli-install.sh


