#!/usr/bin/env bash
echo "==list newest bucket"

# | .[0:5] | 
# add this pipe after the reverse pipe
# if you want to list top 5 newest buckets
aws s3api list-buckets | jq -r '.Buckets | sort_by(.CreationDate) | reverse | .[0] | .Name'
