#!/usr/bin/env bash
echo "==deploy s3 bucket via CFN"


STACK_NAME="cfn-s3-simple"

#https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/deploy.html
aws cloudformation deploy \
--template-file template.yaml \
--stack-name $STACK_NAME \
--region us-east-1 \
--no-execute-changeset
